### ISSUE TITLE
Getting the following error in Matlab

### ISSUE THREAD

**Issue by ac0397** [ArminHuber/Dispersion-Calculator#1]
>> DispersionCalculator
Unrecognized function or variable 'MaterialList'.

Error in DispersionCalculator (line 81)
a.Materials = MaterialList; % load materials from "MaterialList_Fluid.txt", "MaterialList_Isotropic.txt", "MaterialList_TransverselyIsotropic.txt", and "MaterialList_Orthotropic.txt";
              ^^^^^^^^^^^^

**Comment by ArminHuber** [comment]
See Readme section "Use the code":
"In MATLAB, add the DC_MATLAB_Code folder to the MATLAB path (right-click on the folder -> Add to Path -> Selected Folders and Subfolders)."
